### PR TITLE
Reg tests

### LINKED ISSUE #1583: e2e testing framework

### LINKED ISSUE #1639: missing regression tests
- [x] gateway (reimburstment, message cost)
- [x] smoke (grpc, evm, tss)
- [x] fetch prices
- [x] cctp
- [ ] shard offline
- [x] restart (chronicle, validator, rpc)

### PR DESCRIPTION
**Pull request by dvc94ch**
Our new QA testing infra

- [x] get it working locally
- [x] get it working in ci
- [x] port/add all our tests
- [x] add a few new ones for tss, restarting

out of scope: using snapshots to speed things up, left for followup

Closes #1583 
Closes #1639

### CODE REVIEW

File: e2e-tests/src/lib.rs [hunk 1]
```diff
@@ -1 +1,358 @@
...
+use std::collections::HashMap;
+use std::ops::{Deref, DerefMut};
+use std::path::Path;
+use tc_cli::{
+	config::{ConfigYaml, ContractsConfig, GlobalConfig, NetworkConfig},
+	Config, Mnemonics, NetworkId, Sender, Tc,
+};
+use tempfile::TempDir;
+use testcontainers::{
+	//core::logs::consumer::logging_consumer::LoggingConsumer,
```
Comment (haider-rs) [inline e2e-tests/src/lib.rs]: missed to remove?

File: e2e-tests/src/lib.rs [hunk 2]
```diff
@@ -1 +1,358 @@
...
+			.start()
+			.await?;
+		let validator_host = validator.get_host().await?;
+		let validator_port = validator.get_host_port_ipv4(9944).await?;
+		let validator_url = format!("ws://{validator_host}:{validator_port}");
+		let workspace =
+			Path::new(&std::env::var("CARGO_MANIFEST_DIR")?).parent().unwrap().to_path_buf();
+		tracing::info!("workspace: {}", workspace.display());
+		tracing::info!("tempdir: {}", temp.path().display());
+		Ok(Self {
```
Comment (haider-rs) [inline e2e-tests/src/lib.rs:73]: wasnt it better to just read the config file?

File: e2e-tests/src/lib.rs [hunk 3]
```diff
@@ -1 +1,358 @@
...
+		shard_threshold: u16,
+	) -> Result<()> {
+		// add chain to docker compose
+		let chain_name = format!("{}-chain-evm-{network}", &self.network);
+		let chain = GenericImage::new("ghcr.io/foundry-rs/foundry", "latest")
+			.with_exposed_port(8545.tcp())
+			.with_container_name(&chain_name)
+			.with_network(self.network.clone())
+			.with_env_var("ANVIL_IP_ADDR", "0.0.0.0")
+			//.with_log_consumer(LoggingConsumer::new())
```
Comment (haider-rs) [inline e2e-tests/src/lib.rs]: some more comments maybe you missed

**Review by haider-rs — APPROVED** [review]
looks Good, just not sure about the task submitter. i guess we can see the result once we run 4/6 shard config and check chronicle balances.

File: chronicle/src/tasks/mod.rs [hunk 4]
```diff
@@ -233,22 +201,56 @@ impl TaskExecutor {
...
+					target_block_height,
+					task.start_block(),
+				);
+				continue;
+			}
+
+			tracing::info!(parent: &span, "task started");
+
 			let exec = self.params.clone();
+<<<<<<< HEAD
```
Comment (agryaznov) [inline chronicle/src/tasks/mod.rs]: unresolved merge conflict

File: pallets/members/Cargo.toml [hunk 5]
```diff
@@ -33,7 +33,7 @@ time-primitives.workspace = true
 
 [dev-dependencies]
 env_logger.workspace = true
-lazy_static = "1.4.0"
+lazy_static = "1.5.0"
```
Comment (agryaznov) [inline pallets/members/Cargo.toml]: looks like worth moving to workspace.dependencies

File: runtime/Cargo.toml [hunk 6]
```diff
@@ -21,8 +21,8 @@ separator = "0.4.1"
 [dependencies]
 log = { workspace = true }
 
-hex-literal = "0.4.1"
-smallvec = "1.8.0"
+hex-literal = "1.0.0"
```
Comment (agryaznov) [inline runtime/Cargo.toml]: looks like worth moving to workspace.dependencies

File: tc-cli/src/lib.rs [hunk 7]
```diff
@@ -771,6 +775,41 @@ impl Tc {
 }
 
 impl Tc {
+<<<<<<< HEAD
```
Comment (agryaznov) [inline tc-cli/src/lib.rs]: .

File: tc-cli/src/loki.rs [hunk 8]
```diff
@@ -33,150 +33,229 @@ struct StreamValue {
...
+	#[arg(long)]
+	pub gmp_task: Option<String>,
+	#[arg(long)]
+	pub gmp_shard_id: Option<ShardId>,
+	#[arg(long)]
+	pub gmp_events: Option<String>,
+}
+
+impl Log {
+	pub fn matches(&self, other: &Log) -> bool {
```
Comment (agryaznov) [inline tc-cli/src/loki.rs:102]: why not `impl PartialEq for Log` ?

File: tc-cli/src/main.rs [hunk 9]
```diff
@@ -437,83 +432,8 @@ async fn real_main() -> Result<()> {
...
 			let _ = tc.exec_smoke(src, dest, &testers, vec![42]).await?;
-			let (block_hash, _) = tc.latest_block().await?;
-			tc.assert_reimbursement(block_hash).await?;
-			let total_balance_after = tc.total_gateway_balance(block_hash).await?;
-			tc.println(
-				None,
-				format!("made {}$ of profit with msg", total_balance_after - total_balance),
-			)
-			.await?;
-			anyhow::ensure!(total_balance_after >= total_balance);
```
Comment (agryaznov) [inline tc-cli/src/main.rs:485]: why remove balance assertions?

File: e2e-tests/src/lib.rs [hunk 10]
```diff
@@ -1 +1,353 @@
...
+		let temp = TempDir::new()?;
+		let network = temp
+			.path()
+			.file_name()
+			.unwrap()
+			.to_str()
+			.unwrap()
+			.strip_prefix('.')
+			.unwrap()
+			.to_string();
```
Comment (agryaznov) [inline e2e-tests/src/lib.rs:46]:
```suggestion
			.and_then(OsStr::to_str).map(|s| s.trim_start_matches('.').to_string()).unwrap();
```

File: e2e-tests/src/lib.rs [hunk 11]
```diff
@@ -1 +1,353 @@
...
+	}
+
+	/// Returns the tester.
+	pub fn tester(&self, network: NetworkId) -> Result<Address> {
+		Ok(self.testers.get(&network).context("missing tester")?.0)
+	}
+
+	/// Runs a smoke test
+	pub async fn smoke_test(&self, payload: Vec<u8>) -> Result<GmpMessage> {
+		self.exec_smoke(0, 1, &self.testers, payload).await
```
Comment (agryaznov) [inline e2e-tests/src/lib.rs]:
```suggestion
		self.tc.exec_smoke(0, 1, &self.testers, payload).await
```

File: tc-cli/src/main.rs (hunk 9 above)
Comment (dvc94ch) [reply tc-cli/src/main.rs:485]: its in the e2e tests now called gateway payments, this slows smoke test quite a bit

File: e2e-tests/src/lib.rs (hunk 10 above)
Comment (dvc94ch) [reply e2e-tests/src/lib.rs:46]: why is this better?

File: tc-cli/src/loki.rs (hunk 8 above)
Comment (dvc94ch) [reply tc-cli/src/loki.rs:102]: PartialEq works different. we assume `None == Some(_)`. it's not even symmetric. `a.matches(b) != b.matches(a)`

File: e2e-tests/src/lib.rs (hunk 2 above)
Comment (dvc94ch) [reply e2e-tests/src/lib.rs:73]: why? we have a custom config file for each test. in addition to that the ports for example are different on each run, the urls too.
