### PR TITLE
staking: repeat missed events in migration

### LINKED ISSUE #1685: Unable to Withdraw Unbonded Tokens - Insufficient Funds Error
**Environment**: Staging

**Description**: When attempting to withdraw unbonded tokens from the staking page, I encounter an error after signing and submitting the transaction. The error message displayed is "DelegatedStaking: Not enough funds."

**Steps to Reproduce**

- Navigate to the staking page on the staging environment.
- Click on "Accounts" to view unbonded tokens.
- Click on "Withdraw Unbounded" and proceed with the transaction.
- Sign and submit the transaction.
- Error message "DelegatedStaking: Not enough funds" is displayed.
- Expected Result: The unbonded tokens should be successfully withdrawn without any errors.

https://analogapp.slack.com/archives/C08AY31LTJP/p1741757721425109

An error message "DelegatedStaking: Not enough funds" appears, preventing the transaction from finalizing.

### PR DESCRIPTION
**Pull request by FlorianFranzen**
Attempt at executing the bindings of missed events.

- [x] Add staging data (indexer is running...)
- [x]  Run internal test at end to ensure consistency (try-runtime)

### CODE REVIEW

File: runtime/src/configs/staking.rs [hunk 1]
```diff
@@ -402,6 +403,42 @@ impl pallet_delegated_staking::Config for Runtime {
...
+
+const POOL_STAKER: AccountId = AccountId::new(sp_core::hex2array!(
+	"6d6f646c74696d656e6d706c0001000000000000000000000000000000000000"
+));
+
+impl<T: frame_system::Config + pallet_delegated_staking::Config>
+	frame_support::traits::OnRuntimeUpgrade for RepeatMissedStakingEvents<T>
+{
+	fn on_runtime_upgrade() -> Weight {
+		// Wrap storage migration indside transactions that reverts on failure
```
Comment (libreamartists) [inline runtime/src/configs/staking.rs:423]:
```suggestion
		// Wrap storage migration inside transactions that reverts on failure
```

**Comment by FlorianFranzen** [comment]
Was tested successfully on staging, will be deployed to mainnet next.

**Review by peektism — APPROVED** [review]
I do not know how to review these changes, but trust that Florian did it correctly

**Comment by peektism** [comment]
is there a separate PR hooking up the event listener that I missed?

**Comment by FlorianFranzen** [comment]
> is there a separate PR hooking up the event listener that I missed?

Yes, this was fixed earlier in #1706. On mainnet this now repeats the withdrawl in block 1036342, 1104770 and 1186884.

File: runtime/src/configs/staking.rs (hunk 1 above)
Comment (FlorianFranzen) [reply runtime/src/configs/staking.rs:423]: Will be removed again, will try to fix it next time I use this template. :-D
