### PR TITLE
[gmp] fill in EIP1559 estimated gas fees

### LINKED ISSUE #1772: Transaction underpriced on BNB chain
**Description**

The following error happens on integration environment when running any command that involves BNB transactions (`deploy`, `smoke-test`, `benchmark`, etc.):

```
ErrorResp(
    ErrorPayload {
        code: -32000,
        message: "transaction underpriced: gas tip cap 1, minimum needed 1000000000",
        data: None,
    },
)
```

**Steps to Reproduce**

1. Make sure to use the correct integration `config.yaml` and `.env` file
2. Run `tc-cli --env config/envs/integration` benchmark
3. Observe the logs

### PR DESCRIPTION
**Pull request by agryaznov**
should fix https://github.com/Analog-Labs/timechain/issues/1772

### CODE REVIEW

File: gmp/evm/src/lib.rs [hunk 1]
```diff
@@ -358,7 +368,9 @@ impl IConnectorAdmin for Connector {
 		shards.sort_by(|a, b| a.xCoord.cmp(&b.xCoord));
 		let call = Gateway::setShardsCall { publicKeys: shards };
 		let tx = TransactionRequest::default().with_to(a_addr(gateway)).with_call(&call);
+		let tx = self.fill_eip1159_fees(tx).await?;
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]: instead of adding this before every submit, why not do it in submit?

File: gmp/evm/src/lib.rs [hunk 2]
```diff
@@ -552,9 +553,40 @@ impl IConnectorAdmin for Connector {
 }
 
 impl Connector {
+	async fn fill_eip1159_fees(&self, tx: TransactionRequest) -> Result<TransactionRequest> {
+		let estimate = self.estimate_eip1559_fees().await?;
+		Ok(tx
+			.with_max_fee_per_gas(estimate.max_fee_per_gas)
+			.with_max_priority_fee_per_gas(estimate.max_priority_fee_per_gas))
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]: this can be inlined in the submit function

**Review by dvc94ch — COMMENTED** [review]
this works now on BNB? did you test it?

File: gmp/evm/src/lib.rs (hunk 2 above)
Comment (agryaznov) [reply gmp/evm/src/lib.rs]: yeah just tried to save some LoCs here by DRYing it a bit

**Review by dvc94ch — APPROVED** [review]

File: gmp/evm/src/lib.rs [hunk 3]
```diff
@@ -152,8 +153,9 @@ impl IChain for Connector {
 			.with_from(sponsor)
 			.with_to(a_addr(self.address()))
 			.with_value(U256::from(balance));
-
+		let tx = self.fill_eip1159_fees(tx).await?;
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]: missed one here

File: gmp/evm/src/lib.rs [hunk 4]
```diff
@@ -552,9 +546,40 @@ impl IConnectorAdmin for Connector {
 }
 
 impl Connector {
+	async fn fill_eip1159_fees(&self, tx: TransactionRequest) -> Result<TransactionRequest> {
+		let estimate = self.estimate_eip1559_fees().await?;
+		Ok(tx
+			.with_max_fee_per_gas(estimate.max_fee_per_gas)
+			.with_max_priority_fee_per_gas(estimate.max_priority_fee_per_gas))
+	}
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]:
```suggestion
```

File: gmp/evm/src/lib.rs [hunk 5]
```diff
@@ -563,6 +588,7 @@ impl Connector {
 		&self,
 		tx: TransactionRequest,
 	) -> Result<WithOtherFields<TransactionReceipt<AnyReceiptEnvelope<Log>>>> {
+		let tx = self.fill_eip1159_fees(tx).await?;
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]:
```suggestion
		let estimate = self.estimate_eip1559_fees().await?;
		let tx = tx
			.with_max_fee_per_gas(estimate.max_fee_per_gas)
			.with_max_priority_fee_per_gas(estimate.max_priority_fee_per_gas));
```

File: gmp/evm/src/lib.rs (hunk 3 above)
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]:
```suggestion

```

File: gmp/evm/src/lib.rs [hunk 6]
```diff
@@ -563,6 +581,10 @@ impl Connector {
 		&self,
 		tx: TransactionRequest,
 	) -> Result<WithOtherFields<TransactionReceipt<AnyReceiptEnvelope<Log>>>> {
+		let estimate = self.estimate_eip1559_fees().await?;
+		let tx = tx
+			.with_max_fee_per_gas(estimate.max_fee_per_gas)
+			.with_max_priority_fee_per_gas(estimate.max_priority_fee_per_gas));
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]:
```suggestion
			.with_max_priority_fee_per_gas(estimate.max_priority_fee_per_gas);
```

File: gmp/evm/src/lib.rs [hunk 7]
```diff
@@ -552,9 +545,34 @@ impl IConnectorAdmin for Connector {
 }
 
 impl Connector {
+
```
Comment (dvc94ch) [inline gmp/evm/src/lib.rs]:
```suggestion
```
